---
title: "NOAA_Project"
author: "Savinay"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{NOAA_Project}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
## Objective
This is part of R Capstone project. In this project I am analyzing the NOAA dataset.

## Extract data
NOAA data was extracetd from their website and kept in data_raw folder.

## Loading data
Data can be loaded by using load_data function.

```
NOAA_df_raw<-load_data()
```

## Cleaning data
For this I have created a function eq_clean_data. The input is raw data which was generated in the previous step and out is modified dataframe. It internally uses eq_clean_location function.

```
eq_location_clean <- function(df){
  df <- df %>% dplyr::mutate(CLEAN_LOCATION_NAME = stringr::str_trim(gsub(".*:","", LOCATION_NAME))) %>%
    dplyr::mutate(CLEAN_LOCATION_NAME = stringr::str_to_title(CLEAN_LOCATION_NAME))
  return(df)
}

eq_clean_data<-function(raw_data){
  clean_df <- raw_data %>%
    dplyr::mutate(DATE = as.Date(paste0(YEAR,'-',MONTH,'-',DAY), format="%Y-%m-%d")) %>%
    dplyr::mutate(LATITUDE = as.numeric(LATITUDE), LONGITUDE = as.numeric(LONGITUDE)) %>%
    dplyr::mutate(FLAG_TSUNAMI = as.factor(FLAG_TSUNAMI))
  clean_df2<-eq_location_clean(clean_df)
  return(clean_df2)
}
```

## Using Geoms: geom_timeline is created to show the earthquakes for a given country. It also shows the number of deaths that have occured. It is required to enter the year parameter.
##In the example I am using China and USA as parameters and using year>2000.


```
NOAA_df<-eq_clean_data(NOAA_df_raw)

NOAA_df_China_USA <- NOAA_df %>% filter(COUNTRY %in% c("CHINA", "USA"), YEAR > 2000)


ggplot(NOAA_df_China_USA, aes(x = DATE, y = COUNTRY,
               color = as.numeric(TOTAL_DEATHS),
               size = as.numeric(EQ_PRIMARY),
               label = CLEAN_LOCATION_NAME)) +
  geom_timeline() +
  labs(size = "Richter scale value", color = "# deaths") +
  ggplot2::theme(panel.background = ggplot2::element_blank(),
                 legend.position = "bottom",
                 axis.title.y = ggplot2::element_blank()) +
  ggplot2::xlab("DATE")



ggplot(NOAA_df_China_USA , aes(x = DATE, y = COUNTRY,
               color = as.numeric(TOTAL_DEATHS),
               size = as.numeric(EQ_PRIMARY),
               label = CLEAN_LOCATION_NAME)) +
  geom_timeline() +
  labs(size = "Richter scale value", color = "# deaths") +
  ggplot2::theme(panel.background = ggplot2::element_blank(),
                 legend.position = "bottom",
                 axis.title.y = ggplot2::element_blank()) +
  ggplot2::xlab("DATE") +
  geom_timeline_label(data=NOAA_df_China_USA)
  
```

## Using Geom labels: I have created Geom labels to show the location details.


```
NOAA_df<-eq_clean_data(NOAA_df_raw)

NOAA_df_China_USA <- NOAA_df %>% filter(COUNTRY %in% c("CHINA", "USA"), YEAR > 2000)
ggplot(NOAA_df_China_USA, aes(x = DATE, y = COUNTRY,
               color = as.numeric(TOTAL_DEATHS),
               size = as.numeric(EQ_PRIMARY),
               label = LOCATION_NAME)) +
  geom_timeline() +
  labs(size = "Richter scale value", color = "# deaths") +
  ggplot2::theme(panel.background = ggplot2::element_blank(),
                 legend.position = "bottom",
                 axis.title.y = ggplot2::element_blank()) +
  ggplot2::xlab("DATE") +
  geom_timeline_label(data=NOAA_df_China_USA)
```

## Mapping 1: I am also using leaflet to show earthquakes on a map. In this I am going to use Mexico as country and Year>2000.

```
NOAA_df<-eq_clean_data(loaded_data)
df_Mexico <- NOAA_df %>% filter(COUNTRY %in% c("MEXICO"), YEAR > 2000)
map1<-eq_map(df_Mexico,annot_col = "date")
print(map1)

```

## Mapping 2: In this I have created labels for the number of deaths and other features. This is to make the map more interactive.

```
NOAA_df<-eq_clean_data(loaded_data)
df_Mexico <- NOAA_df %>% filter(COUNTRY %in% c("MEXICO"), YEAR > 2000)
map2<-df_Mexico %>% dplyr::mutate(popup_text = eq_create_label(.)) %>%
  eq_map(annot_col = "popup_text")
print(map2)

```
